final_countdown:
    build: ./final_countdown
    volumes:
        - ./final_countdown/home:/home/final_countdown:ro
        - ./final_countdown/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10202:4597"
    expose:
        - "4597"

name:
    build: ./name
    volumes:
        - ./name/home:/home/name:ro
        - ./name/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10203:4597"
    expose:
        - "4597"

memo_manager:
    build: ./memo_manager
    volumes:
        - ./memo_manager/home:/home/memo_manager:ro
        - ./memo_manager/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10204:4597"
    expose:
        - "4597"

joke:
    build: ./joke
    volumes:
        - ./joke/home:/home/joke:ro
        - ./joke/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10205:4597"
    expose:
        - "4597"
